### PR TITLE
Created CLI game main menu and start

### PR DESCRIPTION
**Pull request by Zain-Zameer**
I created CLI of main menu and start for our project.

### CODE REVIEW

**Comment by shivam821** [comment]
Can you explain the code.

**Comment by Zain-Zameer** [comment]
Explanation of the code:

When we run the code, on top there will be heading of our game, Then there are three options available for user to pick. These options are:
1- Start Game
2- Options
3- Exit

let's suppose user clicks on start game button, The game will show four options then:
1 - New Game
2- Load Game
3 - Help/Instructions
4 - Exit

If user clicks on new game button, The game will say "Welcome Newbie!", then asks user to enter his/her name. After that our game will provide user "Game ID" which i created using random function ,there will be characters and numbers in a random ID. This ID will be used for accessing the load game part. 

If user clicks on load game button, the game will ask the user to enter his Game ID, then it will show a button to continue the game.

If user clicks on help/instructions button, game will show this output for the guide of users "If you are new to the game just press start game and enter your name, after that you will get your specific ID which you can use later for continue the game from where you left off."

If user clicks on exit button, user will be returned to our main menu homepage. 


Now on homepage, If user clicks on options button, the game will show all the options that user will use to interact with the game. 


So thats the explanation of my code of main menu and start menu CLI.

**Comment by shivam821** [comment]
Hi @Zain-Zameer , this sounds great. If possible can you also start taking up other tasks as well.

**Comment by Zain-Zameer** [comment]
Sure! 👍

**Pull request merged**
